version: '2'
services:
  ssl:
    image: dockercloud/haproxy
    environment:
      - SSL_CERT=$SSL_CERT
    ports:
      - 80:80
      - 443:443
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: $YOUR_IMAGE
    ports:
      - '8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SERVICE=postgres
      - DB_PORT=5432
  postgres:
    restart: always
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgres/data'
volumes:
  postgres-data:
    driver: local
